const express = require('express')
const cors = require('cors')
const app = express()
const ClienteRoutes = require('./routes/ClienteRoutes')
const IngredienteRoutes = require('./routes/IngredienteRoutes')
app.use(express.json())
app.use(cors({credentials: true, 
    origin: 'http://localhost:3000'}))
app.use(express.static('public'))
app.use('/clientes',ClienteRoutes)
app.use('/ingredientes',IngredienteRoutes)
app.listen(5000)